#ifndef INCLUDE_CSTM_STATE_CFG_H_
#define INCLUDE_CSTM_STATE_CFG_H_

/* to enable tracing UNcomment the following line */
/*#define DBGPRN_ENABLED
 */

#define CSTM_CFG_CHECKED_BUILD_ENABLED

#define CSTM_CFG_ON_ENTER_STATE_ENABLED
#define CSTM_CFG_GET_INPUT_ENABLED
#define CSTM_CFG_SET_OUTPUT_ENABLED
#define CSTM_CFG_ON_LEAVE_STATE_ENABLED


#endif /* INCLUDE_CSTM_STATE_CFG_H_ */
