#ifndef CUSTOM_TRANSITION_ENUM_H_INCLUDED
#define CUSTOM_TRANSITION_ENUM_H_INCLUDED

typedef enum custom_state_transition_enum_tag
{
  TR_NONE,

  TR_POWER_ON_VENT_ON_FIRST_TIME,
  TR_VENT_ON_FIRST_TIME_VENT_OFF,

  TR_VENT_OFF_VENT_ON_DARK_ROOM,
  TR_VENT_ON_DARK_ROOM_VENT_OFF,

  TR_VENT_OFF_VENT_ON_WET_ROOM,
  TR_VENT_ON_WET_ROOM_VENT_OFF,

  TR_POWER_ON_VENT_FAIL,
  TR_VENT_ON_FIRST_TIME_VENT_FAIL,
  TR_VENT_OFF_VENT_FAIL,
  TR_VENT_ON_DARK_ROOM_VENT_FAIL,
  TR_VENT_ON_WET_ROOM_VENT_FAIL,

  TR_COUNT
} custom_state_transition_enum_t;

#endif /* CUSTOM_TRANSITION_ENUM_H_INCLUDED */
